version: "3.2"
services:

  test-cloud-db:
    build:
      context: cloud/db
      args:
        DB_PASSWORD: sec_ctrl_test123
    environment:
        DB_NAME: sec_ctrl_test
        DB_USER: sec_ctrl_test
    ports:
      - "2346:5432"


  cloud-db:
    #image: sec-ctl-db
    build:
      context: cloud/db
      args:
        DB_NAME: sec_ctrl_dev
    environment:
        DB_USER: sec_ctrl_dev
        DB_PASSWORD: sec_ctrl_dev123
    ports:
      - "5678:5432"
    volumes:
      - ".docker-state/db-dev:/var/lib/postgresql/data"

  cloud-redis:
    image: redis:4.0

  # cloud:
  #   image: sec-ctl-cloud
  #   ports:
  #     - 9753:9753
  #   links:
  #     - cloud-db:db
  #     - cloud-redis:redis
  #   environment:
  #     - "SecCtl.Cloud.DBHost=db"

  # local:
  #   image: sec-ctl-local
  #   links:
  #     - mock:mock
  #     - cloud:cloud
  #     - local-redis:redis
  #   environment:
  #     - SecCtl.Local.TPIHost=mock
  #     - SecCtl.Local.TPIPassword=mock123
  #     - SecCtl.Local.CloudWSURL=ws://cloud:9754/ws
  #     - SecCtl.Local.CloudToken=cloud123
  #   ports:
  #     - 9752:9752
  #   volumes:
  #     - "./local-config.json:/root/.config/sec-ctl/Local.json"

  # local-redis:
  #   image: redis:4.0

  # mock:
  #   image: sec-ctl-mock
  #   volumes:
  #     - ".docker-state/mock-state.json:/mock-state.json"
  #   environment:
  #     - "SecCtl.Mock.StateFilename=/mock-state.json"
  #   ports:
  #     - 9751:9751
  #     - 4025:4025

