CREATE USER :DB_USER with password :'DB_PASSWORD';
CREATE DATABASE :DB_NAME owner :DB_USER;


\c :DB_NAME
CREATE SCHEMA ext;
CREATE EXTENSION pgcrypto WITH SCHEMA ext;

GRANT USAGE ON SCHEMA ext TO :DB_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA ext TO :DB_USER;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ext TO :DB_USER;

ALTER SCHEMA public OWNER to :DB_USER;
