export const errorCodeDescriptions: { [code: number]: string } = Object.freeze({
  1: "Receive Buffer Overrun",
  2: "Receive Buffer Overflow",
  3: "Transmit Buffer Overflow",
  10: "Keybus Transmit Buffer Overrun",
  11: "Keybus Transmit Time Timeout",
  12: "Keybus Transmit Mode Timeout",
  13: "Keybus Transmit Keystring Timeout",
  14: "Keybus Interface Not Functioning",
  15: "Keybus Busy",
  16: "Keybus Busy Lockout",
  17: "Keybus Busy Installers Mode",
  18: "Keybus Busy General Busy",
  20: "API Command Syntax Error",
  21: "API Command Partition Error",
  22: "API Command Not Supported",
  23: "API System Not Armed",
  24: "API System Not Ready to Arm",
  25: "API Command Invalid Length",
  26: "API User Code not Required",
  27: "API Invalid Characters in Command",
});
